### ISSUE TITLE
Script not detecting bait in my inventory

### ISSUE THREAD

**Issue by imZesk** [Lunar-Scripts/lunar_fishing#1]
![image](https://github.com/Lunar-Scripts/lunar_fishing/assets/62694810/5eb3699f-64e0-4a00-b066-64d0d5d5eb3a)

![Captura de pantalla 2024-02-25 212710](https://github.com/Lunar-Scripts/lunar_fishing/assets/62694810/07382947-8bb0-4004-9efa-89f59406f0e7)

Im using Origen Inventory in esx 1.10.4

That are the exports: https://docs.origennetwork.store/esx/origen_inventory/exports-origen_inventory

**Comment by KostaZx** [comment]
same issue with ox_inventory

**Comment by imZesk** [comment]
```
local function getBestBait(player)
    for i = #Config.baits, 1, -1 do
        local bait = Config.baits[i]

        if player:getItemCount(bait) > 0 then
            return bait
        end
    end
end
```

The problem is in this function

**Comment by ComoSans** [comment]
same issue with ox_inventory, following

**Comment by NikoClapz19** [comment]
i have the same issue as well with ox_inventory on QB Core

**Comment by DPrpDev** [comment]
Im also getting this error along with this issue;

[script:lunar_fishing] SCRIPT ERROR: @lunar_fishing/utils/sv_main.lua:49: attempt to call a nil value (field 'getItems')
[script:lunar_fishing] > fn (@lunar_fishing/utils/sv_main.lua:49)

**Comment by Lunar-Scripts** [comment]
Just pushed a few changes, redownload the script and let me know if that fixed it for you.
