### ISSUE TITLE
Notification after catching a fish

### ISSUE THREAD

**Issue by KostaZx** [Lunar-Scripts/lunar_fishing#3]
I receive the notification 'You entered a coral reef' every time after I catch the fish.

**Comment by Lunar-Scripts** [comment]
Framework?

**Comment by KostaZx** [comment]
qbox

**Comment by Lunar-Scripts** [comment]
Fixed with v1.0.1

**Comment by KostaZx** [comment]
still happens in swamp territory

**Comment by JasonSteeleLee** [comment]
It is still renotifying in Deep Waters as well.

**Comment by KostaZx** [comment]
yeap same issue
