### ISSUE TITLE
error when selling fish, (ox)

### ISSUE THREAD

**Issue by ComoSans** [Lunar-Scripts/lunar_fishing#4]
![image](https://github.com/Lunar-Scripts/lunar_fishing/assets/153391626/6da9f694-9d85-4c6d-a829-9b337948d098)

**Comment by Lunar-Scripts** [comment]
Are you using ox_inventory?

**Comment by ComoSans** [comment]
yes

**Comment by Lunar-Scripts** [comment]
This isn't related to the script but to your framework.
