### ISSUE TITLE
SCRIPT ERROR: @lunar_fishing/client/main.lua

### ISSUE THREAD

**Issue by EgidijusKiller** [Lunar-Scripts/lunar_fishing#5]
![Screenshot_2](https://github.com/Lunar-Scripts/lunar_fishing/assets/161503497/eea7895a-c2af-4272-8bac-ac56f24ff7f7)
how fix

**Comment by Ixona65** [comment]
> ![Screenshot_2](https://private-user-images.githubusercontent.com/161503497/308278460-eea7895a-c2af-4272-8bac-ac56f24ff7f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTg5ODQsIm5iZiI6MTcwOTA1ODY4NCwicGF0aCI6Ii8xNjE1MDM0OTcvMzA4Mjc4NDYwLWVlYTc4OTVhLWMyYWYtNDI3Mi04YmFjLWFjNTZmMjRmZjdmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxODMxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODI5NGU5MjI5ZDdjMzcxNTkzN2IxOTViZmE4NTRiYzRlZWI2YjMzMmU3NjlhYjRmZDU3ZGQ5YmRhMDhiYmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fn1oD36V6ERs5XHHx4MXvt79LW_B7aj4jsgYx6BKx1Q) how fix

same issues

**Comment by Tomlec7** [comment]
Same problem looks like the ESX Bridge is done incorectly

**Comment by SkRuTzZy** [comment]
QBCore Fix here. 
ESX not sure if it works. Should be working fine.

Code:
---@param level number

local blips = {}

local function updateBlips(level)
    for _, blip in ipairs(blips) do
        if blip.normal then
            RemoveBlip(blip.normal)
        end
        if blip.radius then
            RemoveBlip(blip.radius)
        end
    end

    table.wipe(blips)

    for _, zone in ipairs(Config.fishingZones) do
        if zone.blip and zone.minLevel and level and zone.minLevel <= level then
            for _, coords in ipairs(zone.locations) do
                local blip = Utils.createBlip(coords, {
                    name = zone.blip.name,
                    sprite = zone.blip.sprite,
                    color = 0,
                    scale = zone.blip.scale
                })
                local radiusBlip = Utils.createRadiusBlip(coords, zone.radius, zone.blip.color)
                
                table.insert(blips, { normal = blip, radius = radiusBlip })
            end
        end
    end
end


---@param level number

local zones = {}

local function updateZones(level)
    for _, zone in ipairs(zones) do
        zone:remove()
    end

    table.wipe(zones)

 -- Assuming level is retrieved from somewhere else in your code
 local level = GetPlayerLevel() -- Replace this with the actual function to retrieve the player's level

 if level then
     for index, data in ipairs(Config.fishingZones) do
         if data.minLevel and data.minLevel <= level then
             for locationIndex, coords in ipairs(data.locations) do
                 local zone = lib.zones.sphere({
                     coords = coords,
                     radius = data.radius,
                     onEnter = function()
                         currentZone = { index = index, locationIndex = locationIndex }
     
                         if data.message then
                             ShowNotification(data.message.enter, 'success')
                         end
                     end,
                     onExit = function()
                         if currentZone and (currentZone.index ~= index or currentZone.locationIndex ~= locationIndex) then
                             return
                         end
     
                         currentZone = nil
     
                         if data.message then
                             ShowNotification(data.message.exit, 'inform')
                         end
                     end
                 }) -- Removed extra closing curly brace here
     
                 table.insert(zones, zone)
             end
         end
     end
 else
     print("Warning: Player level is nil.")
 end
 
 
 ---@param level integer
 function Update(level)
     updateBlips(level)
     updateZones(level)
 end
 end 
 
 local function createRodObject()
     local model = `prop_fishing_rod_01`
 
     lib.requestModel(model)
 
     local coords = GetEntityCoords(cache.ped)
     local object = CreateObject(model, coords.x, coords.y, coords.z, true, true, false)
     local boneIndex = GetPedBoneIndex(cache.ped, 18905)
 
     AttachEntityToEntity(object, cache.ped, boneIndex, 0.1, 0.05, 0.0, 70.0, 120.0, 160.0, true, true, false, true, 1, true)
     SetModelAsNoLongerNeeded(model)
 
     return object
 end
 
 local function hasWaterInFront()
     if IsPedSwimming(cache.ped) or IsPedInAnyVehicle(cache.ped, true) then
         return false
     end
     
     local headCoords = GetPedBoneCoords(cache.ped, 31086, 0.0, 0.0, 0.0)
     local coords = GetOffsetFromEntityInWorldCoords(cache.ped, 0.0, 45.0, -27.5)
     local hasWater = TestProbeAgainstWater(headCoords.x, headCoords.y, headCoords.z, coords.x, coords.y, coords.z)
 
     if not hasWater then
         ShowNotification(locale('no_water'), 'error')
     end
 
     return hasWater
 end
 
 lib.callback.register('lunar_fishing:getCurrentZone', function()
     return hasWaterInFront(), currentZone
 end)
 
 local function setCanRagdoll(state)
     SetPedCanRagdoll(cache.ped, state)
     SetPedCanRagdollFromPlayerImpact(cache.ped, state)
     SetPedRagdollOnCollision(cache.ped,statefalse)
 end
 
 ---@param bait FishingBait
 ---@param fish Fish
 lib.callback.register('lunar_fishing:itemUsed', function(bait, fish)
     local zone = Config.fishingZones[currentZone] or Config.outside
 
     local object = createRodObject()
     lib.requestAnimDict('mini@tennis')
     lib.requestAnimDict('amb@world_human_stand_fishing@idle_a')
     setCanRagdoll(false)
     ShowUI(locale('cancel'), 'ban')
 
     local p = promise.new()
 
     local interval = SetInterval(function()
         if IsControlPressed(0, 38)
         or (not IsEntityPlayingAnim(cache.ped, 'mini@tennis', 'forehand_ts_md_far', 3)
         and not IsEntityPlayingAnim(cache.ped, 'amb@world_human_stand_fishing@idle_a', 'idle_c', 3)) then
             HideUI()
             p:resolve(false)
         end
     end, 100) --[[@as number?]]
 
     local function wait(milliseconds)
         Wait(milliseconds)
 
         return p.state == 0
     end
 
     CreateThread(function()
         TaskPlayAnim(cache.ped, 'mini@tennis', 'forehand_ts_md_far', 3.0, 3.0, 1.0, 16, 0, false, false, false)
 
         if not wait(1500) then return end
 
         TaskPlayAnim(cache.ped, 'amb@world_human_stand_fishing@idle_a', 'idle_c', 3.0, 3.0, -1, 11, 0, false, false, false)
 
         if not wait(math.random(zone.waitTime.min, zone.waitTime.max) / bait.waitDivisor * 1000) then return end
 
         ShowNotification(locale('felt_bite'), 'warn')
         HideUI()
 
         if interval then
             ClearInterval(interval)
             interval = nil
         end
 
         if not wait(math.random(2000, 4000)) then return end
 
         local success = lib.skillCheck(fish.skillcheck, { 'e' })
 
         if not success then
             ShowNotification(locale('catch_failed'), 'error')
         end
 
         p:resolve(success)
     end)
 
     local success = Citizen.Await(p)
 
     if interval then
         ClearInterval(interval)
         interval = nil
     end
 
     DeleteEntity(object)
     ClearPedTasks(cache.ped)
     setCanRagdoll(true)
 
     return success
 end)

**Comment by Zeniah100** [comment]
Hi @SkRuTzZy, I did try and replace that code for my QBcore server and it didn't work. Gave me another error. I originally had the same error as the other guys.
![Screenshot_28](https://github.com/Lunar-Scripts/lunar_fishing/assets/161542469/fe40a175-4cd2-4fb6-a90a-a3b3098c9dd7)

**Comment by SkRuTzZy** [comment]
> Hi @SkRuTzZy, I did try and replace that code for my QBcore server and it didn't work. Gave me another error. I originally had the same error as the other guys. ![Screenshot_28](https://private-user-images.githubusercontent.com/161542469/308391506-fe40a175-4cd2-4fb6-a90a-a3b3098c9dd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMDkzMTUsIm5iZiI6MTcwOTIwOTAxNSwicGF0aCI6Ii8xNjE1NDI0NjkvMzA4MzkxNTA2LWZlNDBhMTc1LTRjZDItNGZiNi1hOTBhLWEzYjMwOThjOWRkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQxMjE2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjRiNGVmZTc2MjBmMTdhYmRlZjNiNDQxMmM3ODJiMGM0MTRkZTMzYzU5ZDU1MDBmZDA2NzEwYWFiOTRmM2I4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nMzxRgQWGWKn8J3byO33Em4cI3VmZgp9VNid62VbJLc)

I have the file already fixed. Didin't remember to add to this post. Heres the script for the client folder and level.lua file.

`local level = 1

-- Assuming Update is defined elsewhere in your codebase
function Update(newLevel)
    -- Implementation of the Update function
end

---@param l number
local function updated(l)
    level = l
    Update(level)
end

-- Assuming lib is defined and callback is a valid function in your library
lib.callback('lunar_fishing:getLevel', false, updated)

RegisterNetEvent('esx:playerLoaded', function()
    lib.callback('lunar_fishing:getLevel', false, updated)
end)

RegisterNetEvent('QBCore:Client:OnPlayerLoaded', function()
    lib.callback('lunar_fishing:getLevel', false, updated)
end)

RegisterNetEvent('lunar_fishing:updateLevel', updated)

function GetCurrentLevel()
    return math.floor(level)
end

function GetCurrentLevelProgress()
    return level - math.floor(level)
end
`
