### ISSUE TITLE
Boat bugged

### ISSUE THREAD

**Issue by Sylvernl88** [Lunar-Scripts/lunar_fishing#6]
After you rent a boat and you press F to leave the steering you cant get back behind the steering wheel even when you not anchor your boat

the seat is now walktrought

![image](https://github.com/Lunar-Scripts/lunar_fishing/assets/81586511/67c1c70e-a822-4be4-b17a-03411002d433)

**Comment by Lucasmillen1** [comment]
Is it just for this boat or all

**Comment by Lunar-Scripts** [comment]
Fixed with v1.0.1
