### ISSUE TITLE
A lot of issues

### ISSUE THREAD

**Issue by JungleKitty132** [Lunar-Scripts/lunar_fishing#7]
[              STDERR] (node:1605487) UnhandledPromiseRejectionWarning: Error: BUFFER_SHORTAGE
[              STDERR]     at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
[              STDERR]     at h (citizen:/scripting/v8/msgpack.js:29:15761)
[              STDERR]     at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
[              STDERR]     at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
[              STDERR]     at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
[              STDERR]     at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
[              STDERR]     at unpack (citizen:/scripting/v8/main.js:50:33)
[              STDERR]     at citizen:/scripting/v8/main.js:82:21
[              STDERR]     at Number.__cfx_wrap_41432 (citizen:/scripting/v8/main.js:23:12)
[              STDERR]     at citizen:/scripting/v8/main.js:29:16
[              STDERR] (node:1605487) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[script:lunar_fishing] SCRIPT ERROR: @lunar_fishing/server/level.lua:5: lunar_fishing was unable to execute a query!
[script:lunar_fishing] Query: SELECT * FROM lunar_fishing
[script:lunar_fishing] []
[script:lunar_fishing] Table 'zap1185762-1.lunar_fishing' doesn't exist
[script:lunar_fishing] > cb (@lunar_fishing/server/level.lua:5)
[script:lunar_fishing] > onReady (@oxmysql/lib/MySQL.lua:128)
[script:lunar_fishing] > fn (@oxmysql/lib/MySQL.lua:135)
[script:lunar_fishing] > logError (@oxmysql/dist/build.js:26272)
[script:lunar_fishing] > rawQuery (@oxmysql/dist/build.js:26447)
[script:lunar_fishing] > processTicksAndRejections (node:internal/process/task_queues:96)
[             TXADMIN] txaReportResources

**Comment by Lucasmillen1** [comment]
Did you add the sql?

**Comment by JungleKitty132** [comment]
Yeah i have SQL
