### ISSUE TITLE
Blip for deep sea and Swamp missing

### ISSUE THREAD

**Issue by Brave-developments** [Lunar-Scripts/lunar_fishing#9]
I've correctly installed the latest version , and i am using new qbcore but despite my efforts, I can't seem to get the deep-sea activity blip to appear on the map.
<img width="626" alt="image" src="https://github.com/Lunar-Scripts/lunar_fishing/assets/89262662/f2dbdcde-7afe-4afe-bd98-c0bb61ef40f7">

**Comment by Brave-developments** [comment]
sorry i didnt check the client side files. So those blips works with level system?

**Comment by Lunar-Scripts** [comment]
Yes, those work with the level system
